### ISSUE TITLE
401 getting user data after Slack oauth, app doesn't render

### ISSUE THREAD

**Issue by mmartinson** [FoundersAS/walkiebot#8]
This may have something do to with me misconfiguring the redirect URL, but after the slack oauth succeeds I'm getting nothing rendered on the redirect and `api/users/me` is getting 401

![image](https://user-images.githubusercontent.com/6256333/40747162-4c1f6944-6411-11e8-8e5d-3d846ddd0822.png)

Browser url is `https://*****.herokuapp.com/login?next=&token=******`

`localStorage.user_token` has the same value as the token in the url

**Comment by alexagranov** [comment]
@mmartinson Walkie is currently setup to listen for the Slack login on `/slack/login` - https://github.com/FoundersAS/walkiebot/blob/master/server/handlers/slack.js#L61

So your Redirect_URL configuration on your Slack App "OAuth & Permissions" page should point to your HTTPS Heroku App DNS + `/slack/login`

**Comment by mmartinson** [comment]
@alexagranov thanks. I have that url configured on the slack oauth and permissions page, but that doesn't seem to do it. Do I need to configure `SLACK_LOGIN_REDIRECT_URL` in the environment with the matching url? That is what I have now and I'm still getting no page load after the redirect. 

What is unexplained for me here is that the url bar in the browser after the oauth has `/login` not `/slack/login`. Does that seem off to you?

**Comment by alexagranov** [comment]
@mmartinson The `/login` after successful OAuth is expected: https://github.com/FoundersAS/walkiebot/blob/master/server/handlers/slack.js#L119-L122

You do need to have `SLACK_LOGIN_REDIRECT_URL` configured, I just checked my Heroku config and mine is set to: `****.herokuapp.com/slack/login`

I think your issue may be elsewhere.  Have you set up your JWT public/secret keys appropriately so that requests are passing validation?  They have to be in a particular format: https://github.com/FoundersAS/walkiebot/pull/2#issuecomment-389598431

**Comment by mmartinson** [comment]
Got it. Thank you. It was an issue with the JWT keys. I had read the mentioned comment and misconfigured them.
